export const ActionTypes = {
  FETCH_CATEGORY_FILTERS: "FETCH_CATEGORY_FILTER",
  FETCH_CATEGORY_FILTERS_SUCCESS: "FETCH_CATEGORY_FILTER_SUCCESS",
  FETCH_CATEGORY_FILTERS_FAILURE: "FETCH_CATEGORY_FILTER_FAILURE",
};
